# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180226_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
