# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='user',
        ),
        migrations.AlterField(
            model_name='authentication',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
